export const JustProductDB = [
    {
        id:1,
        Image:"/IMG/Paste image (6).png",
        proDesc:"96 Nuptse Dip Dye Korea Puffers Jacket",
        rating:5,
        price:"$500",
        countInStock:0,
    },
    {
        id:2,
        Image:"/IMG/Paste image (5).png",
        proDesc:"Paradigm Chilliwack Black Label Jacket",
        rating:4,
        price:"$400",
        countInStock:7,
    },
    {
        id:3,
        Image:"/IMG/Paste image.png",
        proDesc:"1996 Retro Nuptse Jacket in Black",
        rating:4,
        price:"$500",
        countInStock:7,
    },
    {
        id:4,
        Image:"/IMG/Paste image (14).png",
        proDesc:"Paul Quilted Nylon Puffer bomber jacket",
        rating:3,
        price:"$300",
        countInStock:7,
    },
    {
        id:5,
        Image:"/IMG/Paste image (2).png",
        proDesc:"Chilliwack jacket Bomber HUMANATURE",
        rating:5,
        price:"$500",
        countInStock:7,
    },
    {
        id:6,
        Image:"/IMG/Paste 4.png",
        proDesc:"96 Nuptse Dip Dye Korea Puffers Jacket",
        rating:5,
        price:"$500",
        countInStock:7,
    },
    {
        id:7,
        Image:"/IMG/Paste image (17).png",
        proDesc:"96 Nuptse Dip Dye Korea Puffers Jacket",
        rating:4,
        price:"$200",
        countInStock:7,
    },
    {
        id:8,
        Image:"/IMG/Paste image (16).png",
        proDesc:"96 Nuptse Dip Dye Korea Puffers Jacket",
        rating:3,
        price:"$400",
        countInStock:7,
    },
    {
        id:9,
        Image:"/IMG/Paste image (7).png",
        proDesc:"96 Nuptse Dip Dye Korea Puffers Jacket",
        rating:4,
        price:"$200",
        countInStock:7,
    }
]